--- #YAML:1.0
name: Shell-Parser
version: 0.01
author:
  - |-
    Sébastien Aperghis-Tramoni <sebastien@aperghis.net>
abstract: The great new Shell::Parser!
license: perl
requires:
  Carp: 0
  Test::More: 0
provides:
  Shell::Parser:
    file: lib/Shell/Parser.pm
    version: 0.01
generated_by: Module::Build version 0.26
